# Numpy Basics <hr style="border:2px solid #ff0000"><hr>

<b>Tovi R. Macalisay</b>
<br>Comp Tech Student

# Imports and Packages

In [1]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D array

In [2]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [3]:
np.shape(my_array)

(3,)

# 2D Array

In [4]:
v_array = np.array([
    [1,2,3],
    [4,5,6]
])
v_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.shape(v_array)

(2, 3)

# 3D Array

In [6]:
t_array = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
t_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
np.shape(t_array)

(3, 2, 3)

# Measures of Central Tendancey

In [8]:
# Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [9]:
np.shape(resistance)

(2, 11)

In [10]:
res_mean = np.nanmean(resistance, axis=1)
res_mean

array([ 9.4 , 10.75])

In [11]:
print("Jaguar Mean:", (res_mean[0]).round(2), "ohms")

Jaguar Mean: 9.4 ohms


In [12]:
round(res_mean[0])
(res_mean[0]).round(2)

print(f'jaguar: {res_mean[0]:.2f} ohms')
print(f'panther: {res_mean[1]:.2f} ohms')


jaguar: 9.40 ohms
panther: 10.75 ohms


In [13]:
res_median = np.nanmedian(resistance, axis=1)
res_median

array([9.8 , 9.55])

In [14]:
print(f'jaguar: {res_median[0]:.2f} ohms')
print(f'panther: {res_median[1]:.2f} ohms')

jaguar: 9.80 ohms
panther: 9.55 ohms


In [15]:
res_mode = stats.mode(resistance, axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [16]:
jag_res = resistance[0]
print("Jaguar mode: ")
for i in multimode(jag_res):
    print(i, "ohms")

Jaguar mode: 
9.8 ohms
10.4 ohms


In [17]:
pan_res = resistance[1]
print("panther mode: ")
for i in multimode(pan_res):
    print(i, "ohms")

panther mode: 
9.1 ohms


# Measure of Variability

In [18]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [19]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [20]:
print("jaguar range:", res_range[0], "ohms")
print("panther range:", res_range[1], "ohms")

jaguar range: 8.0 ohms
panther range: 10.9 ohms


In [21]:
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [22]:
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [23]:
print("jaguar IQR:", f"{res_Q3[0]-res_Q1[0]:.2f}", "ohms")
print("jaguar IQR:", f"{res_Q3[0]-res_Q1[0]:.2f}", "ohms")

jaguar IQR: 1.05 ohms
jaguar IQR: 1.05 ohms


In [24]:
res_var = np.nanvar(resistance, axis=1)
res_var

array([4.41818182, 9.9745    ])

In [25]:
%pip install statsmodels --upgrade


Note: you may need to restart the kernel to use updated packages.
